# Generated by Django 3.1 on 2022-01-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='photos/categories')),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'b2c_features"."category',
                'managed': False,
            },
        ),
    ]
