# Generated by Django 3.1 on 2022-03-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviewrating',
        ),
    ]
